language: python
python:
    - 2.7
    - 3.7
install: sudo apt-get update -q && sudo apt-get install -y -q mpich libmpich-dev && pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: "jappa"
  password:
    secure: "Nok+LErR6EirXXGIA9advfMIwTy8E2gdr1ObSdXF7N2L9uL51SSo3Zz2AdzkmlscsQVI426WvARHatKAQwe9PTdvOtPoE8UOmC/REbTvEuRKNUlv/nFV69RODfA3XhYIGNX8rEXU01VA56dkeW3iIacMOIAyP5DiKVqSkrLRZ1fBJCfm2+KAlo/Wvigk14pBLqZFR92XVoS77Imz2j9WHq9QDroS368Rw3kwNZwyhhd8LSZBHRXW8+lVUP7Za6ohXbyjzO3syTDmQmTG/64CguZ0+MCSVocbkJSp8n/wITARu1zZ7hw2jeChVdxs42ifR/UFa2pXCgN41Uk9xkJBwIG/j/R5dokB3FdjfpoO6BIuJfNLZcp4Iwi9GRkOFaN0po+vnUSPrjYOBBIXrz8qG5EOTR8bNtXTQsQZa4kSkbFBCpT/DNDoeyRM2pNP3Zs/RCGZMi6xytEw5+HoaC7vy+4Mu2FoOfQ5RJvyoAKRuNKgJQLhF2vg6nB99aOPBfHygJL6uLMK4TYuapaW0ZhA4xh1QvLDDE6Mo6Z458MbNBhEfYvJC+qNyq8AekA0TpTjJHoVg+jw47Mxnzg8HmnSoGirTNyN4bc/4QGtMuC32z7sBy6xVf6Lpzg6LZphjpkVgv9dU8U5dN3qwaGmYpkQ+Pm3LL73ZPdi6NZnsBRibpY="
  on:
    tags: true
    branch: master
  skip_cleanup: true
  skip_existing: true
