language: python
python:
- 2.7
- 3.7
install: sudo apt-get update -q && sudo apt-get install -y -q mpich libmpich-dev &&
  pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: "__token__" 
  password:
    secure: Wy+GLDZsJ4o10MV0Gp8FP2rP23ghxmnwdx0ittJhHvvfqTCTFxFzCzY+pJ8lVlboATBp+tDJjwkAPoT4qotUjYe/ne+q5tNlof1kTjGxHGxYF5aik0AXSjmVCa7hKFT0wDnVgk1HQ01X/gqH8EgywiNbOORM8BkgAmqYHbFbBbY0GKMUTiqc6wqy6GCI4QJdKYm2x9wEN1qwZ++XA8RpCAHXnwrwEQIdLufWA1ulvA9ug/Mh+lucgTcWFb+E3oScA8XUSSizXPJWtl0JnaT8AKAORRoC4Fxhs2ozZcgNgCOVkyjgoFQhVb/H30VGc4J6idkY2QB3bTDT3h80azpadnlQAA37qjzcs3PVGlzGa+jCs9BU3UFFoHaeKLIrMDx5T9uZBikEL4/w8hoDE/PTa6fs3eF9eFUETWRJZaYE1LXscGnwMr4u6EXh8rME45WzOGQ2C//srERK+vhYXK0226EvCgMrzl2zSFhpB1XChfNmrbyMBlJiG6LRTg0UbrTjDxvyb8mUvv+91ar6fGgKnxeuIyQ4ha/ePZxN6Vk+0PGI5jI3xjGKJGgcDza4jleTd8xXXkqC2gzLbBE0SxS3MWs1+KDb3YwPdQMDVFSIHgO2jSSmlHA+VOoE441bwd8I8ytkSmt94tRv7zv4zlgPKgTVU0X1A+86CRGdZAM7JkM=
  on:
    tags: true
    branch: master
  skip_cleanup: true
  skip_existing: true
